
build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    dependencies:
        override:
            - "composer install --no-dev --prefer-source"
            - "cd example && composer install --no-dev --prefer-source && cd .."

filter:
    paths: ["src/*", "example/*.php"]
    dependency_paths:
        - vendor/
        - example/vendor/

tools:
    external_code_coverage:
        timeout: 600
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["vendor"]
    php_loc:
        enabled: true
        excluded_dirs: ["vendor"]
    php_mess_detector:
        enabled: true
        config:
            ruleset: phpmd.xml.dist
            design_rules: { eval_expression: false }
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["tests", "vendor", "fixtures"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*"]
    sensiolabs_security_checker: true
