name: CI

on: [push, pull_request]

jobs:
  testsuite:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4', '8.0', '8.1']
        composer-opts: ['']
        include:
          - php-version: '7.1'
            composer-opts: '--prefer-lowest'

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: xdebug

    - name: Composer install
      run: |
        if [[ ${{ matrix.php-version }} == '8.0' || ${{ matrix.php-version }} == '8.1' ]]; then
          composer remove --dev squizlabs/php_codesniffer phpstan/phpstan-shim phpunit/phpunit
          composer require --dev phpunit/phpunit:^8.5
        else
          composer update ${{ matrix.composer-opts }}
        fi

    - name: Run PHPUnit
      run: |
        if [[ ${{ matrix.php-version }} == '7.4' ]]; then
          vendor/bin/phpunit -v --debug --coverage-clover=coverage.clover
        else
          vendor/bin/phpunit --no-coverage
        fi

    - name: Code Coverage Report
      if: matrix.php-version == '7.4'
      run: |
        wget https://scrutinizer-ci.com/ocular.phar
        php ocular.phar code-coverage:upload --format=php-clover coverage.clover;

  cs-stan:
      name: Coding Standard & Static Analysis
      runs-on: ubuntu-18.04

      steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: cs2pr

      - name: Composer Install
        run: composer install

      - name: Run phpcs
        run: vendor/bin/phpcs --report=checkstyle -q --standard=PSR2 --warning-severity=0 src/ tests/Test | cs2pr

      - name: Run phpstan
        if: success() || failure()
        run: vendor/bin/phpstan.phar analyse src/ tests/ --no-progress --level 2
