name: CI

on: [push, pull_request]

jobs:
  testsuite:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.1', '7.4', '8.0']
        composer-opts: ['']
        include:
          - php-version: '7.1'
            composer-opts: '--prefer-lowest'

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: pcov

    - name: Composer install
      run: |
        composer update ${{ matrix.composer-opts }}

    - name: Run PHPUnit
      run: |
        if [[ ${{ matrix.php-version }} == '7.4' ]]; then
          vendor/bin/phpunit --process-isolation -v --debug --coverage-clover=coverage.clover
        else
          vendor/bin/phpunit --process-isolation
        fi

    - name: Code Coverage Report
      if: matrix.php-version == '7.4'
      run: |
        wget https://scrutinizer-ci.com/ocular.phar
        php ocular.phar code-coverage:upload --format=php-clover coverage.clover;

  cs-stan:
      name: Coding Standard
      runs-on: ubuntu-18.04

      steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: cs2pr

      - name: Composer Install
        run: composer install

      - name: Run phpcs
        run: vendor/bin/phpcs --standard=PSR2 --report=emacs --extensions=php --warning-severity=0 src/ tests/Test
        run: vendor/bin/phpcs --report=checkstyle -q --standard=PSR2 --warning-severity=0 src/ tests/Test | cs2pr
